# Generated by Django 5.2.7 on 2025-11-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_date_issued'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='booking_ownder',
            new_name='booking_owner',
        ),
    ]
